const MOCK_TRANSACTIONS = [
  "Payment transaction at Wisoky, O'Conner and Conn",
  "Deposit transaction at Daugherty Inc",
  "Deposit transaction at McKenzie Group",
  "Invoice transaction at Frami - Sipes",
  "Withdrawal transaction at Dietrich and Sons",
  "Invoice transaction at Volkman - Jacobs",
  "Payment transaction at Stracke LLC",
  "Deposit transaction at Hermiston Inc",
  "Withdrawal transaction at Mueller Group",
  "Payment transaction at Kassulke, Witting and Gutkowski",
  "Deposit transaction at Hoppe Group",
  "Payment transaction at Prohaska - Walter",
  "Deposit transaction at Reynolds - Larkin",
  "Payment transaction at O'Keefe, Parker and Mertz",
  "Invoice transaction at Murphy, Jenkins and Gislason",
  "Payment transaction at Aufderhar, Franey and Schulist",
  "Invoice transaction at Dooley - Kreiger",
  "Withdrawal transaction at Predovic Group",
  "Withdrawal transaction at MacGyver - McDermott",
  "Payment transaction at Stracke Inc",
  "Withdrawal transaction at Gulgowski LLC",
  "Payment transaction at Fay, Mueller and Lindgren",
  "Payment transaction at Beatty, Zemlak and Casper",
  "Withdrawal transaction at Wisozk Group",
  "Payment transaction at Nader, Wolf and Runolfsdottir",
  "Deposit transaction at Smith and Sons",
  "Invoice transaction at Bartoletti - Treutel",
  "Payment transaction at Wisozk - Koepp",
  "Deposit transaction at Beier - Wolf",
  "Invoice transaction at Conn - Dooley",
  "Invoice transaction at Hand - Orn",
  "Payment transaction at Weissnat, Kiehn and Braun",
  "Payment transaction at Wiegand - Pouros",
  "Invoice transaction at Bernier, Schmitt and Lebsack",
  "Deposit transaction at Greenfelder LLC",
  "Invoice transaction at Sanford, Trantow and Mosciski",
  "Payment transaction at Cruickshank, Treutel and Gerlach",
  "Invoice transaction at O'Kon, Prosacco and Strosin",
  "Deposit transaction at Mohr LLC",
  "Withdrawal transaction at Glover - Streich",
  "Withdrawal transaction at Reinger, Leffler and Huel",
  "Invoice transaction at Hamill Group",
  "Payment transaction at Connelly - Hamill",
  "Invoice transaction at Windler - Skiles",
  "Payment transaction at Lockman, Morar and Gutmann",
  "Withdrawal transaction at Sawayn, Johns and Tillman",
  "Deposit transaction at Wilderman - Anderson",
  "Invoice transaction at Cassin, Turner and Klocko",
  "Payment transaction at Huel, Doyle and Lubowitz",
  "Invoice transaction at McClure, Johnston and Zieme",
];

export default MOCK_TRANSACTIONS;
